### ISSUE TITLE
Why R can only read first 93 row of rpp_data.csv ?

### ISSUE THREAD

**Issue by hcp4715** [CenterForOpenScience/rpp#10]
Dear experts,

Apologize for cross posting.
I am trying to re-run the RPP data on my PC, but encountered a problem that quite weird and can't solve myself:
I run the masterscript.r and found that R could only read first 93 rows, the 94th started with an author name instead of study ID (see the picture [here](https://lh3.googleusercontent.com/-rJTjMnyKLrk/V5fjGP74KcI/AAAAAAAAAsA/7O2bAFUfwu0CIFbUGyjKJTFRDPD5tzfuQCLcB/s1600/FF53.tm.png))! 
Many thanks in advance!

My system information is as following:

R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by hcp4715** [comment]
I found a solution online, finally.
what I need to do is : add one line,

Sys.setlocale("LC_ALL", "English")

 maybe this code could be added to the masterscript.r, so that researchers using other language could use the script directly.

**Comment by chartgerink** [comment]
That is a good suggestion, I added the line into `masterscript.R`. :-) Thanks!
