### ISSUE TITLE
I can't figure out why you didn't just use the correlation coefficients for these studies? 

### ISSUE THREAD

**Issue by jtleek** [CenterForOpenScience/rpp#7]
Is there a reference or a reason you calculated the coverage using the F distribution, etc. for these statistics rather than just using the Fisher transform on the correlation coefficient? 

https://github.com/CenterForOpenScience/rpp/blob/c15f3f0bae1353bb2e949163f8c864af6e1f4123/masterscript.R#L551-L694

**Comment by chartgerink** [comment]
For these statistics, the standard error of the Fisher transformed correlation statistic cannot be calculated, hence coverage cannot be calculated using this statistic. Therefore, we used the noncentral distribution of the F and chi2 statistic, of which the distribution is known exactly

**Comment by jtleek** [comment]
Can you point me to the reference where the transform for the F + chisq2 statistic with multiple dof can be transformed into a correlation coefficient and the reference where you can calculate the standard error for the cases where there is only a single dof test? Thanks

**Comment by chartgerink** [comment]
Please see the [Appendix](https://osf.io/z7aux/) of the paper for more information.

**Comment by jtleek** [comment]
Ok. It wasn't clear there. There was no reference. Thanks.
